# Generated by Django 5.1.1 on 2024-10-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metier', '__first__'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date_debut', models.DateField(max_length=25, null=True)),
                ('date_fin', models.DateField(max_length=25, null=True)),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='metier.metier')),
            ],
        ),
    ]
